# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f7972f4a90e7e34360db1a7fe7eb93ec84b8e906f8113226834501ba1efbdc64c699f8f38af20ac50e7586de9d13a16395fb7d8e06cf9cade0ed10d6f71ddb7

test:
  secret_key_base: a4c1bf12c93be33f5be1baf1ad5b7f76a42f3b8b6a19e73d78dcf43f1433ed964c4f14641082b91047fea3df824b2d3f06ed30dc8e36b127d7bc07a09a4a6c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
